# Use an official Python runtime as a base image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /sandbox/temp

# Default command to keep the container focused
CMD ["python3"]
